# Generated by Django 5.1.15 on 2026-05-05 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='bibliografia',
            new_name='biografia',
        ),
    ]
